name: Create a release pull request

on:
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  github-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a release pull request
        id: create-pr
        uses: takeyama-h1/test@master
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: prerelease
          GIT_PR_RELEASE_LABELS: "for master"

      - name: Slack Notification on Nothing Pull Request
        if: "${{ success() && steps.create-pr.outputs.no_pr == 'true' }}"
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,job
          custom_payload: |
            {
              text: `:white_check_mark: ${process.env.AS_REPO} にリリース対象のPRはありませんでした。`,
              attachments: [{
                "fields":[
                  {
                    "title": "Job",
                    "value": `${process.env.AS_JOB}`,
                    "short": false
                  }
                ]
              }]
            }

      - name: Slack Notification on Success
        if: "${{ success() && steps.create-pr.outputs.no_pr == 'false' }}"
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,job
          custom_payload: |
            {
              text: `:white_check_mark: ${process.env.AS_REPO} で リリースPRの作成に成功しました。`,
              attachments: [{
                color: 'good',
                "fields":[
                  {
                    "title": "Pull Request",
                    "value": "${{steps.create-pr.outputs.pr_url}}",
                    "short": false
                  },
                  {
                    "title": "Job",
                    "value": `${process.env.AS_JOB}`,
                    "short": false
                  }
                ]
              }]
            }

      - name: Slack Notification on Failure
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: custom
          fields: repo,job
          custom_payload: |
            {
              text: `:warning: ${process.env.AS_REPO} で リリースPRの作成に失敗しました。`,
              attachments: [{
                color: 'danger',
                "fields":[
                  {
                    "title": "Job",
                    "value": `${process.env.AS_JOB}`,
                    "short": false
                  }
                ]
              }]
            }
