name: Create a release pull request

on:
  workflow_dispatch:

env:
  HAPPYHOTEL_PR_NOTIFICATION_WEBHOOK_URL: ${{ secrets.HAPPYHOTEL_PR_NOTIFICATION_WEBHOOK_URL }}

jobs:
  github-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a release pull request
        id: create-pr
        uses: takeyama-h1/test@master
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: prerelease
          GIT_PR_RELEASE_LABELS: "for master"

      - name: Slack Notification on Nothing Pull Request
        if: "${{ success() && steps.create-pr.outputs.no_pr == 'true' }}"
        run: |
          jq -n -M '{
            "cards": [
              {
                "header": {
                  "title": "リリース対象のPR作成がされませんでした。"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "keyValue": {
                          "topLabel": "Repository",
                          "content": "${{ github.repository }}",
                          "onClick": {
                            "openLink": {
                              "url": "https://github.com/${{ github.repository }}"
                            }
                          }
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Workflow",
                          "content": "${{ github.workflow }}",
                          "onClick": {
                            "openLink": {
                              "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }' | curl -H 'Content-Type: application/json; charset=UTF-8' -X POST -d @- "${{ secrets.HAPPYHOTEL_PR_NOTIFICATION_WEBHOOK_URL }}"

      - name: Slack Notification on Success
        if: "${{ success() && steps.create-pr.outputs.no_pr == 'false' }}"
        run: |
          jq -n -M '{
            "cards": [
              {
                "header": {
                  "title": "リリースPR作成に成功しました。"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "<font color=\"#2eb886\">SUCCESS!!</font>"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Repository",
                          "content": "${{ github.repository }}",
                          "onClick": {
                            "openLink": {
                              "url": "https://github.com/${{ github.repository }}"
                            }
                          }
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Pull Request",
                          "content": "${{ steps.create-pr.outputs.pr_url }}",
                          "onClick": {
                            "openLink": {
                              "url": "${{ steps.create-pr.outputs.pr_url }}"
                            }
                          }
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Workflow",
                          "content": "${{ github.workflow }}",
                          "onClick": {
                            "openLink": {
                              "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }' | curl -H 'Content-Type: application/json; charset=UTF-8' -X POST -d @- "${{ secrets.HAPPYHOTEL_PR_NOTIFICATION_WEBHOOK_URL }}"

      - name: Slack Notification on Failure
        if: failure()
        run: |
          jq -n -M '{
            "cards": [
              {
                "header": {
                  "title": "リリースPR作成に失敗しました"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "<font color=\"#ff0000\">WARNING!!</font>"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Repository",
                          "content": "${{ github.repository }}",
                          "onClick": {
                            "openLink": {
                              "url": "https://github.com/${{ github.repository }}"
                            }
                          }
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Workflow",
                          "content": "${{ github.workflow }}",
                          "onClick": {
                            "openLink": {
                              "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                            }
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }' | curl -H 'Content-Type: application/json; charset=UTF-8' -X POST -d @- "${{ secrets.HAPPYHOTEL_PR_NOTIFICATION_WEBHOOK_URL }}"
