name: Create a release pull request

on:
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  githubPrRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a release pull request
        id: create-pr
        uses: takeyama-h1/test@master
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: prerelease
          GIT_PR_RELEASE_LABELS: "for master"

      - name: Slack Notification on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,eventName
          status: success
          text: "${{steps.create-pr.outputs.pr_url}} が作成されました。"

      - name: Slack Notification on Failure
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          fields: repo,eventName
          status: failure
          text: "PRの作成に失敗しました。"
